// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlXfsevo46P5qARbyZ1c3OehFthNcwQRo',
    appId: '1:408736020888:web:69eac2c9fc510a441913ed',
    messagingSenderId: '408736020888',
    projectId: 'gymtelligent-cbccd',
    authDomain: 'gymtelligent-cbccd.firebaseapp.com',
    storageBucket: 'gymtelligent-cbccd.firebasestorage.app',
    measurementId: 'G-NXYFPV2LSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAex5vNh6br7r_pl8nBg3c3_96nVhZZQy8',
    appId: '1:408736020888:android:f2f7ae880c06624e1913ed',
    messagingSenderId: '408736020888',
    projectId: 'gymtelligent-cbccd',
    storageBucket: 'gymtelligent-cbccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB663rgdbC3RMfyiIaVnIuVGYuUunI0YNQ',
    appId: '1:408736020888:ios:58fb005438c41c541913ed',
    messagingSenderId: '408736020888',
    projectId: 'gymtelligent-cbccd',
    storageBucket: 'gymtelligent-cbccd.firebasestorage.app',
    iosBundleId: 'ai.application.gymtelligent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB663rgdbC3RMfyiIaVnIuVGYuUunI0YNQ',
    appId: '1:408736020888:ios:58fb005438c41c541913ed',
    messagingSenderId: '408736020888',
    projectId: 'gymtelligent-cbccd',
    storageBucket: 'gymtelligent-cbccd.firebasestorage.app',
    iosBundleId: 'ai.application.gymtelligent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlXfsevo46P5qARbyZ1c3OehFthNcwQRo',
    appId: '1:408736020888:web:01423cd6c0752f2f1913ed',
    messagingSenderId: '408736020888',
    projectId: 'gymtelligent-cbccd',
    authDomain: 'gymtelligent-cbccd.firebaseapp.com',
    storageBucket: 'gymtelligent-cbccd.firebasestorage.app',
    measurementId: 'G-ZFEEQ92VKJ',
  );
}
